# Generated by Django 5.1 on 2024-12-30 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messagereceipt",
            options={"get_latest_by": "timestamp"},
        ),
        migrations.RemoveField(
            model_name="message",
            name="status",
        ),
    ]
